# Generated by Django 2.1.7 on 2020-03-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=7)),
                ('complement', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('estate', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cel', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('situation', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Customer'),
        ),
        migrations.AddField(
            model_name='adress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Customer'),
        ),
    ]
